[hekad]
base_dir = "/home/heka/"

[HaproxyDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/haproxy_decoder.lua"

[LogstreamerInput]
log_directory = "/var/log/syslog-ng/"
file_match = 'syslog.log'

[PayloadEncoder]
append_newlines = false

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"





