[hekad]
maxprocs = 2
base_dir = "/vagrant/heka"

[LogstreamerInput]
log_directory = "/vagrant/log"
file_match = 'test\.log'
decoder = "MultiDecoder"

[MultiDecoder]
type = "MultiDecoder"
subs = ['HaproxyDecoder', 'RethinkDbDecoder', 'RedisDecoder', 'JsonDecoder']
log_sub_errors = false
cascade_strategy = "first-wins"

[HaproxyDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/haproxy_decoder.lua"

[RedisDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/redis_decoder.lua"

[RethinkDbDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/rethinkdb_decoder.lua"

[JsonDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/json.lua"


[PayloadEncoder]
append_newlines = false

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"

[localServer]
type = "HttpOutput"
message_matcher = "TRUE"
address = "http://127.0.0.1:4000"
encoder = "PayloadEncoder"
[localServer.headers]
Content-Type = ["application/json"]

[FileOutput]
message_matcher = "TRUE"
path = "/vagrant/log/heka_output.log"
perm = "666"
flush_count = 100
flush_operator = "OR"
encoder = "PayloadEncoder"
