[hekad]
base_dir = "/home/heka/"

[LogFileInput]
type = "LogstreamerInput"
log_directory = "/vagrant/log"
file_match = 'test\.log'
decoder = "MultiDecoder"

[MultiDecoder]
type = "MultiDecoder"
subs = ['HaproxyDecoder', 'RedisDecoder']
cascade_strategy = "first-wins"

[HaproxyDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/haproxy_decoder.lua"

[RedisDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/redis_decoder.lua"


[PayloadEncoder]
append_newlines = false

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"

