[hekad]
maxprocs = 2
base_dir = "/home/heka"

[LogstreamerInput]
log_directory = "/vagrant/log"
file_match = 'test\.log'
decoder = "HaproxyDecoder"

[MultiDecoder]
type = "MultiDecoder"
subs = ['HaproxyDecoder', 'RedisDecoder']
cascade_strategy = "first-wins"

[HaproxyDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/haproxy_decoder.lua"

[RedisDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/redis_decoder.lua"


[PayloadEncoder]
append_newlines = false

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"

[FileOutput]
message_matcher = "TRUE"
path = "/vagrant/log/heka_output.log"
perm = "666"
flush_count = 100
flush_operator = "OR"
encoder = "PayloadEncoder"
